In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv('../data/prices_JNJ.csv')
df = df.drop('Date', axis = 'columns')

In [3]:
df.head()

   Adj Close       Close        High         Low        Open    Volume
0  76.173637  100.480003  101.809998   99.449997  101.709999  12722800
1  76.492050  100.900002  101.440002  100.570000  100.580002   6467200
2  76.105408  100.389999  100.970001   99.599998   99.820000   7733800
3  75.218430   99.220001  100.089996   98.879997   99.309998   9433100
4  74.414856   98.160004   99.940002   97.849998   99.879997   9766700

In [4]:
df['ret_1d'] = df['Adj Close'].pct_change()
df['ret_5d'] = df['Adj Close'].pct_change(5)
df['red_20d'] = df['Adj Close'].pct_change(20)
df['vol_5d'] = df['ret_1d'].rolling(5).std()
df['vol_20d'] = df['ret_1d'].rolling(20).std()
df['ma_10'] = df['Adj Close'].rolling(10).mean()
df['ma_20'] = df['Adj Close'].rolling(20).mean()
df['price_to_ma20'] = df['Adj Close'] / df['ma_20'] - 1
df['vol_chg'] = df['Volume'].pct_change()
df['vol_z20'] = (df['Volume'] - df['Volume'].rolling(20).mean())/df['Volume'].rolling(20).std()
df['y_reg'] = df['Adj Close'].pct_change().shift(-1)   
df['y_class'] = (df['y_reg'] > 0).astype(int)

In [5]:
df = df.dropna()
df.head()

,Adj Close,Close,High,Low,Open,Volume,ret_1d,ret_5d,red_20d,vol_5d,vol_20d,ma_10,ma_20,price_to_ma20,vol_chg,vol_z20,y_reg,y_class
20,78.394852,103.410004,104.260002,103.000000,103.300003,10616300,-0.009198,0.022040,0.029160,0.011537,0.015803,76.012145,75.338198,0.040572,0.082887,-0.097366,0.007059,1
21,78.948273,104.139999,104.379997,102.010002,103.650002,10168600,0.007059,0.019382,0.032111,0.011295,0.015841,76.648190,75.461009,0.046213,-0.042171,-0.296495,-0.002305,0
22,78.766312,103.900002,104.089996,102.730003,103.610001,10389000,-0.002305,0.015938,0.034963,0.011603,0.015791,77.251639,75.594054,0.041964,0.021675,-0.277514,-0.032339,0
23,76.219093,100.540001,102.769997,99.779999,102.660004,15522200,-0.032339,-0.037342,0.013303,0.015046,0.017324,77.538956,75.644087,0.007601,0.494100,1.209093,0.014522,1
24,77.325943,102.000000,103.510002,100.220001,100.309998,14323800,0.014522,-0.022708,0.039120,0.018009,0.017361,77.963491,75.789642,0.020271,-0.077206,0.766467,-0.000294,0

In [6]:
os.makedirs("../data/raw", exist_ok=True)
df.to_csv("../data/features_JNJ.csv")